### ISSUE TITLE
Enhancement: Hover state for items in the Inbox

### ISSUE THREAD

**Issue by colinjlacy** [PredixDev/px-inbox#11]
## Expected behavior and actual behavior:
I'd expect that when I hover over an item, there's some sort of hover-state feedback that indicates to the user that the inbox item is interactive.  Currently it shows no feedback when hovering.

## Steps to reproduce the problem:
Navigate to https://www.predix-ui.com/#/elements/px-inbox and hover over an item in the component demo.  Notice that no feedback is given to the user.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
All(?)

## Screenshots (_optional, but very helpful_):
I would, but when I try to take a screenshot the cursor is removed.

**Comment by randyaskin** [comment]
v.2.2.5 - Added color effect, css variable, updated theme/darktheme, and fixed cursor:pointer that was in there already but broken. 👍

**Comment by colinjlacy** [comment]
Much appreciated!
