### ISSUE TITLE
Enhancement: Make the search and sort controls optional

### ISSUE THREAD

**Issue by malinovskymax** [PredixDev/px-inbox#15]
It would be great if the search and sort controls were optional, so px-inbox could be used as a component with a sidebar control for switching some page content.

I expect it to look without these controls like on the screenshot attached.
![px-inbox](https://user-images.githubusercontent.com/13059510/37912329-fbcb7eca-311a-11e8-8fb5-872fb395e09d.png)

**Comment by e-kag** [comment]
@malinovskymax thats a good idea, as part of that it would be worthwhile to add the following properties:
`sort`: true|false
`sortDirection`: ASC|DESC
`sortField`: field to sort on
`search`: true|false
