### ISSUE TITLE
px-inbox list item id should be compared using equality ==

### ISSUE THREAD

**Issue by victorbucutea** [PredixDev/px-inbox#3]
Hi,

This is more of an improvement suggestion, but a likely source of problems - for you to decide.

in **px-inbox.html:164** we are computing the **selected** class by comparing the id of the listItem with the id attribute of the li tag. 
If list is fed from back-end the id of the entitity more than often is an integer (e.g. 1) whereas the id of the li tag is a string "1". When comparing the 2 with an identity operator ( 1 === "1" ) they are not equal and the 'selected' class is not added to the li

## Expected behavior and actual behavior:
<li> item should have a 'selected' class

## Steps to reproduce the problem:
in **/master/demo/index.html** change the id of the 'demoProps' variable to be a number. The item in the li box will not receive a selected tag. 

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
https://github.com/PredixDev/px-inbox/blob/master/demo/index.html#L226 --> comparison should be done via equality
https://github.com/PredixDev/px-inbox/blob/master/px-inbox.html#L165 --> comparison should be done via equality

**Comment by nonmetalhail** [comment]
I see the problem, but dont think `==` is the correct solution due to javascript's  loose falsey definitions. The int `0` could equal too many other falsey values . Should probably stringify the ID instead.

**Comment by randyaskin** [comment]
Fixed in v0.2.29 - thanks!

**Comment by randyaskin** [comment]
Oops, had a bit of confusion with versioning with Elliot's typo fixes - went ahead and tagged the latest as 1.0.0, since bower and semver behave a little odd before 1.0.0 anyway.
