### ISSUE TITLE
when listItems is empty, an exception breaks page execution

### ISSUE THREAD

**Issue by victorbucutea** [PredixDev/px-inbox#4]
Ok, this is another issue which is more of a usability improvement, but if issue occurs it breaks page loading altogether.

## Expected behavior and actual behavior:
When setting the `px-inbox` list-items to a value which is empty ( which happens when it is filled in after an ajax request for example ) I get the following stack trace in the console:

> Uncaught TypeError: Cannot read property 'id' of undefined
    at HTMLElement._formatDates (px-inbox.html:197)
    at HTMLElement._observerEffect (polymer.html:1662)
    at HTMLElement._effectEffects (polymer.html:1507)

## Steps to reproduce the problem:
This happens due to the observed value of the listItems property (  `observer: '_formatDates'` ). when it is nulled out or set to [] - and this might happen if the AJAX request fails and the `listItems` are set to []  - the page will not load (pb due to exception above )

The fix would pb be something like below at `px-inbox.html:186`

` if (!this.listItems || this.listItems.length == 0 ){
        return;
      }`

**Comment by randyaskin** [comment]
Fixed in v0.2.29 - thanks!

**Comment by randyaskin** [comment]
Oops, had a bit of confusion with versioning with Elliot's typo fixes - went ahead and tagged the latest as 1.0.0, since bower and semver behave a little odd before 1.0.0 anyway.
