### ISSUE TITLE
Issue #3 still not resolved 

### ISSUE THREAD

**Issue by victorbucutea** [PredixDev/px-inbox#5]
Guys, 

The commit in https://github.com/PredixDev/px-inbox/commit/c67a0bc309b418195345c9444daaaeb2bf33dc2f doesn't fix the problem.
if selectedId = "1" and id = 1, `JSON.stringify(selectedId)` would return ""1"" ( a string wrapped in quotes ) and "1" ( a number wrapped in quotes )
So if you want to avoid the loose falsey attributes and not use == ( which makes sense btw ), I guess you need to normalize input or something.
`
// this would be false if one is a string and the other an number
 JSON.stringify(selectedId) === JSON.stringify(id) 
`

**Comment by randyaskin** [comment]
Weird, I didn't expect that from JSON.stringify. Anyway, switched to just `String(id)` in v1.0.1 and that seems to do the trick.
