### ISSUE TITLE
Enhancement: allow descending sort order

### ISSUE THREAD

**Issue by brettjohns89** [PredixDev/px-inbox#6]
## Expected behavior and actual behavior:

The sorting capability does not give you any choice whether or not to sort in ascending or descending order, which limits its usefulness and functionality. Sorting by "title" or "subtitle" sorts in ascending order, and "severity" and "date" sort in descending order without any choice in the matter. 

The different severity levels do not give a sufficient level of granularity for a wide range of use cases, so giving the option to sort by descending on the other elements (title, subtitle, or possibly even a hidden field value) would open up many other UX possibilities. 

Our specific use case is having a list of alerts based on probability levels that are dynamically populated, and we want to sort them in descending order of the calculated probability. We can somewhat approximate this by giving different "severity" ratings based on different probability thresholds, but we would really like more granularity than this to differentiate between alerts that are given the same "severity" level (i.e. 75% and 99% probability should not be prioritized the same but with only 4 severity options we have to sort them into these large buckets). Differentiating by "severity" also applies different CSS styles which we have to override. 

It would be much simpler and more straightforward to simply allow descending sort based on subtitle or even a hidden attribute of some sort.

**Comment by randyaskin** [comment]
Added in v2.
