### ISSUE TITLE
Enhancement: make default selection optional

### ISSUE THREAD

**Issue by brettjohns89** [PredixDev/px-inbox#7]
## Expected behavior and actual behavior:

I am using an event listener for "px-inbox-selected-item-changed" to capture when the user selects a new inbox item and have some actions run as a result. 

However, the px-inbox component is currently coded to select the first item in the list on page load, which in turn calls this method. I have built a workaround to ignore the first event, but it would be useful if this were an optional argument in the px-inbox component itself. There are many potential use cases where a default selection on page load is not wanted. 

## Steps to reproduce the problem:

Load the px-inbox component and set a listener for px-inbox-selected-item-changed

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

px-inbox version 1.0.1, all browsers and OSes 

## Code examples:

![image](https://user-images.githubusercontent.com/28303871/27040885-592d6dfa-4f60-11e7-9394-437821a30375.png)

**Comment by randyaskin** [comment]
Added in v2.
